fix: Change span id
martignoni/hugo-cloak-email pull request #11
Opened 2020-03-09 15:43 UTC by kosssi

ID attribute values must be unique

https://dequeuniversity.com/rules/axe/3.5/duplicate-id

2020-03-09 15:44 UTC, kosssi commented
Thanks for this shortcode ;)

2020-03-09 17:21 UTC, martignoni commented
I'd be glad to merge your PR, but I'm afraid I don't understand why the ID attribute is not unique (before your PR). Can you please elaborate?

2020-03-10 11:02 UTC, kosssi commented
@martignoni In your script you can see two same id :
- [`id="id-{{ $fingerprint }}"></span>&#32;`](https://github.com/martignoni/hugo-cloak-email/blob/master/layouts/shortcodes/cloakemail.html#L20)
- [`<script id="id-{{ $fingerprint }}">`](https://github.com/martignoni/hugo-cloak-email/blob/master/layouts/shortcodes/cloakemail.html#L22)

Sorry I'm not explain where is.

2020-03-10 12:18 UTC, martignoni commented
Undestood, you're right. Thanks for the fix.

2020-03-10 13:04 UTC, martignoni commented on layouts/shortcodes/cloakemail.html
> +  #wjs-{{ $fingerprint }}.cloaked-e-mail:before {
```suggestion
  #span-{{ $fingerprint }}.cloaked-e-mail:before {
```

2020-03-10 13:05 UTC, martignoni commented on layouts/shortcodes/cloakemail.html
> +&#32;<span class="cloaked-e-mail" data-user="{{ range $index := seq (sub (len $user) 1) 0}}{{ substr $user $index 1}}{{ end }}"{{ with $domain }} data-domain="{{ range $index := seq (sub (len $domain
```suggestion
&#32;<span class="cloaked-e-mail" data-user="{{ range $index := seq (sub (len $user) 1) 0}}{{ substr $user $index 1}}{{ end }}"{{ with $domain }} data-domain="{{ range $index := seq (sub (len $domain) 1) 0}}{{ substr $domain $index 1}}{{ end }}"{{ end }} id="span-{{ $fingerprint }}"></span>&#32;
```

2020-03-10 13:06 UTC, martignoni requested changes
Suggesting some better ID names.

You could change the other ID too, eg. `"script-{{ $fingerprint }}"` instead of `"id-{{ $fingerprint }}"` (lines 22-23).

2020-03-12 09:58 UTC, kosssi commented
Done ;)

2020-03-13 12:40 UTC, martignoni approved these changes

2020-03-13 12:41 UTC, merged

2020-03-13 12:42 UTC, martignoni commented
Thank you!